version: "0.2"
language: en
words:
  - Abril
  - autobuild
  - autolabeler
  - binstall
  - Fatface
  - filelock
  - htmlcov
  - mkdocs
  - peaceiris
  - pyproject
  - pipx
  - pypi
  - rustup
  - sarif
  - setuptools
  - testpypi
  - venv
  - xianpengshen
  - zizmor
ignorePaths:
  - .env/**
  - .venv/**
  - env/**
  - venv/**
  - .gitignore
